fix: crawls not found page created
ripple/explorer pull request #569
Opened 2023-01-31 21:38 UTC by pdp2121

## High Level Overview of Change

Not all rippled/ entrypoint can be crawled.  In this case we should show users an error message on the Network pages for custom networks.

This issue is present with the hooks testnet and iou escrows testnet.  

[XRPL Hooks Amendment](http://hooks-testnet-v2.xrpl-labs.com/) 
[icv2.ws.transia.co:443](http://icv2.ws.transia.co:443/)

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

### TypeScript/Hooks Update

- [x] Updated files to React Hooks
- [x] Updated files to TypeScript

## Before / After

After the change, the Network tab for networks that cannot be crawls should be as below:

<img width="936" alt="Screenshot 2023-01-31 at 4 36 03 PM" src="https://user-images.githubusercontent.com/71317875/215888890-780e0805-5246-4a52-b579-fbb98bbe4491.png">

2023-01-31 21:49 UTC, ckniffen commented on src/containers/Network/index.tsx
> +const Network = (props: NetworkProps) => {
Use named export.

2023-01-31 21:51 UTC, ckniffen commented on src/containers/Network/index.tsx
> +  const { match } = props
Leverage `useMatch` instead.

2023-01-31 21:55 UTC, ckniffen commented on src/containers/App/App.jsx
> +            ? setNetworkName(null)
Have you tried putting the ternary inside `setNetworkName`?

2023-01-31 21:57 UTC, ckniffen commented on src/containers/Network/index.tsx
> +  const { tab = 'nodes' } = params
Leverage `useParams`

2023-02-03 18:28 UTC, ckniffen approved these changes

2023-02-03 22:12 UTC, mvadari commented on public/locales/en-US/translations.json
> +  "network_cannot_crawled": "This network cannot be crawled",
```suggestion
  "network_cannot_be_crawled": "This network cannot be crawled",
```

2023-02-03 22:13 UTC, mvadari approved these changes

2023-02-03 22:36 UTC, ckniffen commented on src/containers/Network/index.tsx
> +        title="network_cannot_crawled"
```suggestion
        title="network_cannot_be_crawled"
```

2023-02-03 22:36 UTC, ckniffen requested changes
Need to update usage of language key

2023-02-03 22:46 UTC, pdp2121 commented
> Need to update usage of language key

Thanks for noticing that. Made the update, pulled to make sure everything looks right.

2023-02-06 20:17 UTC, merged